### PR TITLE
bugfix:game works fine on phone now

### PR DESCRIPTION
**Pull request by borkarsaish65**
1.Game works fine on mobile tested on Samsung galaxy J7.
2.Fixed chrome issue of reloading game on making the snake go down.
3.Added feature of game reloading after 3 seconds when game is over.

### CODE REVIEW

**Comment by abhi27-web** [comment]
Thank you loads!!!

**Comment by abhi27-web** [comment]
Hey, I added a few css features to it. But earlier on scrolling doen it didn't used to reload but it started reloading again. Could you tell me what went wrong.

**Comment by abhi27-web** [comment]
Hey, I added a few CSS features to it. But earlier on scrolling down, it didn't use to reload as you had corrected that but it started reloading again. Could you tell me what went wrong?
Also, I don't know why the navbar is not visible on the phone.

**Comment by borkarsaish65** [comment]
add this style to body to fix this: overflow-y: hidden;

**Comment by borkarsaish65** [comment]
open issue if you want me to fix anything else

**Comment by abhi27-web** [comment]
I have opened the issue.

**Pull request merged**
